// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ContractAuthority struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	AccessType           string   `protobuf:"bytes,3,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractAuthority) Reset()         { *m = ContractAuthority{} }
func (m *ContractAuthority) String() string { return proto.CompactTextString(m) }
func (*ContractAuthority) ProtoMessage()    {}
func (*ContractAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}
func (m *ContractAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractAuthority.Unmarshal(m, b)
}
func (m *ContractAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractAuthority.Marshal(b, m, deterministic)
}
func (m *ContractAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractAuthority.Merge(m, src)
}
func (m *ContractAuthority) XXX_Size() int {
	return xxx_messageInfo_ContractAuthority.Size(m)
}
func (m *ContractAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_ContractAuthority proto.InternalMessageInfo

func (m *ContractAuthority) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ContractAuthority) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ContractAuthority) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

type Permission struct {
	AuthCategory         string   `protobuf:"bytes,1,opt,name=auth_category,json=authCategory,proto3" json:"auth_category,omitempty"`
	AuthMessage          [][]byte `protobuf:"bytes,2,rep,name=auth_message,json=authMessage,proto3" json:"auth_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetAuthCategory() string {
	if m != nil {
		return m.AuthCategory
	}
	return ""
}

func (m *Permission) GetAuthMessage() [][]byte {
	if m != nil {
		return m.AuthMessage
	}
	return nil
}

type Contract struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Methods              []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Contract) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Contract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Account struct {
	Address              []byte              `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []byte              `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenFund           []byte              `protobuf:"bytes,3,opt,name=frozen_fund,json=frozenFund,proto3" json:"frozen_fund,omitempty"`
	PledgeFund           []byte              `protobuf:"bytes,4,opt,name=pledge_fund,json=pledgeFund,proto3" json:"pledge_fund,omitempty"`
	Nonce                uint64              `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	VarsHash             []byte              `protobuf:"bytes,6,opt,name=vars_hash,json=varsHash,proto3" json:"vars_hash,omitempty"`
	CreditIndex          []byte              `protobuf:"bytes,7,opt,name=credit_index,json=creditIndex,proto3" json:"credit_index,omitempty"`
	State                int32               `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	CreatedTransaction   []byte              `protobuf:"bytes,9,opt,name=created_transaction,json=createdTransaction,proto3" json:"created_transaction,omitempty"`
	ContractVersion      string              `protobuf:"bytes,10,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	Permissions          []*Permission       `protobuf:"bytes,11,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Integral             []*CreditIntegral   `protobuf:"bytes,12,rep,name=integral,proto3" json:"integral,omitempty"`
	HoldContract         []*ContractIntegral `protobuf:"bytes,13,rep,name=hold_contract,json=holdContract,proto3" json:"hold_contract,omitempty"`
	TxCount              uint64              `protobuf:"varint,14,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxsHash              []byte              `protobuf:"bytes,15,opt,name=txs_hash,json=txsHash,proto3" json:"txs_hash,omitempty"`
	Evil                 uint64              `protobuf:"varint,16,opt,name=evil,proto3" json:"evil,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetFrozenFund() []byte {
	if m != nil {
		return m.FrozenFund
	}
	return nil
}

func (m *Account) GetPledgeFund() []byte {
	if m != nil {
		return m.PledgeFund
	}
	return nil
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetVarsHash() []byte {
	if m != nil {
		return m.VarsHash
	}
	return nil
}

func (m *Account) GetCreditIndex() []byte {
	if m != nil {
		return m.CreditIndex
	}
	return nil
}

func (m *Account) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Account) GetCreatedTransaction() []byte {
	if m != nil {
		return m.CreatedTransaction
	}
	return nil
}

func (m *Account) GetContractVersion() string {
	if m != nil {
		return m.ContractVersion
	}
	return ""
}

func (m *Account) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Account) GetIntegral() []*CreditIntegral {
	if m != nil {
		return m.Integral
	}
	return nil
}

func (m *Account) GetHoldContract() []*ContractIntegral {
	if m != nil {
		return m.HoldContract
	}
	return nil
}

func (m *Account) GetTxCount() uint64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *Account) GetTxsHash() []byte {
	if m != nil {
		return m.TxsHash
	}
	return nil
}

func (m *Account) GetEvil() uint64 {
	if m != nil {
		return m.Evil
	}
	return 0
}

type ContractIntegral struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CreatedHeight        uint64   `protobuf:"varint,2,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	ContractTxCount      []byte   `protobuf:"bytes,3,opt,name=contract_tx_count,json=contractTxCount,proto3" json:"contract_tx_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractIntegral) Reset()         { *m = ContractIntegral{} }
func (m *ContractIntegral) String() string { return proto.CompactTextString(m) }
func (*ContractIntegral) ProtoMessage()    {}
func (*ContractIntegral) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}
func (m *ContractIntegral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractIntegral.Unmarshal(m, b)
}
func (m *ContractIntegral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractIntegral.Marshal(b, m, deterministic)
}
func (m *ContractIntegral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractIntegral.Merge(m, src)
}
func (m *ContractIntegral) XXX_Size() int {
	return xxx_messageInfo_ContractIntegral.Size(m)
}
func (m *ContractIntegral) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractIntegral.DiscardUnknown(m)
}

var xxx_messageInfo_ContractIntegral proto.InternalMessageInfo

func (m *ContractIntegral) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContractIntegral) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *ContractIntegral) GetContractTxCount() []byte {
	if m != nil {
		return m.ContractTxCount
	}
	return nil
}

type CreditIntegral struct {
	TermId               uint64   `protobuf:"varint,1,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	Normal               uint64   `protobuf:"varint,2,opt,name=normal,proto3" json:"normal,omitempty"`
	Contract             uint64   `protobuf:"varint,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Template             uint64   `protobuf:"varint,4,opt,name=template,proto3" json:"template,omitempty"`
	DoEvil               uint64   `protobuf:"varint,5,opt,name=do_evil,json=doEvil,proto3" json:"do_evil,omitempty"`
	CollectBlock         uint64   `protobuf:"varint,6,opt,name=collect_block,json=collectBlock,proto3" json:"collect_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditIntegral) Reset()         { *m = CreditIntegral{} }
func (m *CreditIntegral) String() string { return proto.CompactTextString(m) }
func (*CreditIntegral) ProtoMessage()    {}
func (*CreditIntegral) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}
func (m *CreditIntegral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditIntegral.Unmarshal(m, b)
}
func (m *CreditIntegral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditIntegral.Marshal(b, m, deterministic)
}
func (m *CreditIntegral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditIntegral.Merge(m, src)
}
func (m *CreditIntegral) XXX_Size() int {
	return xxx_messageInfo_CreditIntegral.Size(m)
}
func (m *CreditIntegral) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditIntegral.DiscardUnknown(m)
}

var xxx_messageInfo_CreditIntegral proto.InternalMessageInfo

func (m *CreditIntegral) GetTermId() uint64 {
	if m != nil {
		return m.TermId
	}
	return 0
}

func (m *CreditIntegral) GetNormal() uint64 {
	if m != nil {
		return m.Normal
	}
	return 0
}

func (m *CreditIntegral) GetContract() uint64 {
	if m != nil {
		return m.Contract
	}
	return 0
}

func (m *CreditIntegral) GetTemplate() uint64 {
	if m != nil {
		return m.Template
	}
	return 0
}

func (m *CreditIntegral) GetDoEvil() uint64 {
	if m != nil {
		return m.DoEvil
	}
	return 0
}

func (m *CreditIntegral) GetCollectBlock() uint64 {
	if m != nil {
		return m.CollectBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*ContractAuthority)(nil), "corepb.ContractAuthority")
	proto.RegisterType((*Permission)(nil), "corepb.Permission")
	proto.RegisterType((*Contract)(nil), "corepb.Contract")
	proto.RegisterType((*Account)(nil), "corepb.Account")
	proto.RegisterType((*ContractIntegral)(nil), "corepb.ContractIntegral")
	proto.RegisterType((*CreditIntegral)(nil), "corepb.CreditIntegral")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4b, 0x6f, 0xd3, 0x4c,
	0x14, 0x55, 0x1a, 0x37, 0x8f, 0x1b, 0xa7, 0x8f, 0xf9, 0x3e, 0x95, 0x01, 0x16, 0x84, 0x20, 0xa4,
	0xc0, 0xa2, 0x48, 0x85, 0x2d, 0x8b, 0x12, 0x81, 0xda, 0x05, 0x12, 0x1a, 0x45, 0x88, 0x9d, 0x35,
	0x19, 0xdf, 0xc6, 0x16, 0x8e, 0xc7, 0x9a, 0x99, 0x44, 0x09, 0x1b, 0x7e, 0x16, 0x12, 0xbf, 0x0e,
	0xcd, 0x1d, 0xdb, 0x81, 0x2e, 0xba, 0xeb, 0x39, 0xe7, 0xbe, 0x7a, 0xe6, 0x38, 0x30, 0x96, 0x4a,
	0xe9, 0x4d, 0xe9, 0x2e, 0x2b, 0xa3, 0x9d, 0x66, 0x3d, 0xa5, 0x0d, 0x56, 0xcb, 0xe9, 0x1d, 0x9c,
	0xcf, 0x75, 0xe9, 0x8c, 0x54, 0xee, 0x7a, 0xe3, 0x32, 0x6d, 0x72, 0xb7, 0x67, 0x1c, 0xfa, 0x32,
	0x4d, 0x0d, 0x5a, 0xcb, 0x3b, 0x93, 0xce, 0x2c, 0x16, 0x0d, 0x64, 0x17, 0xd0, 0x5b, 0xa3, 0xcb,
	0x74, 0xca, 0x8f, 0x26, 0x9d, 0xd9, 0x50, 0xd4, 0x88, 0x3d, 0x83, 0x91, 0x54, 0x0a, 0xad, 0x4d,
	0xdc, 0xbe, 0x42, 0xde, 0x25, 0x11, 0x02, 0xb5, 0xd8, 0x57, 0x38, 0x5d, 0x00, 0x7c, 0x41, 0xb3,
	0xce, 0xad, 0xcd, 0x75, 0xc9, 0x5e, 0xc0, 0x58, 0x6e, 0x5c, 0x96, 0x28, 0xe9, 0x70, 0xa5, 0xcd,
	0x9e, 0xd6, 0x0c, 0x45, 0xec, 0xc9, 0x79, 0xcd, 0xb1, 0xe7, 0x40, 0x38, 0x59, 0xa3, 0xb5, 0x72,
	0x85, 0xfc, 0x68, 0xd2, 0x9d, 0xc5, 0x62, 0xe4, 0xb9, 0xcf, 0x81, 0x9a, 0x7e, 0x83, 0x41, 0x73,
	0xfd, 0x03, 0x47, 0x73, 0xe8, 0x87, 0x33, 0x2d, 0xcd, 0x18, 0x8a, 0x06, 0x7a, 0x65, 0x8b, 0xc6,
	0x9f, 0x54, 0x9f, 0xdc, 0xc0, 0xe9, 0xef, 0x08, 0xfa, 0xd7, 0xc1, 0xb1, 0x87, 0x27, 0x2f, 0x65,
	0x21, 0x4b, 0x85, 0xe4, 0x47, 0x2c, 0x1a, 0xe8, 0x0d, 0xb9, 0x33, 0xfa, 0x07, 0x96, 0xc9, 0xdd,
	0xa6, 0x4c, 0x69, 0x7a, 0x2c, 0x20, 0x50, 0x9f, 0x36, 0x25, 0x39, 0x56, 0x15, 0x98, 0xae, 0x30,
	0x14, 0x44, 0xa1, 0x20, 0x50, 0x54, 0xf0, 0x3f, 0x1c, 0x97, 0xda, 0x4f, 0x3e, 0x9e, 0x74, 0x66,
	0x91, 0x08, 0x80, 0x3d, 0x85, 0xe1, 0x56, 0x1a, 0x9b, 0x64, 0xd2, 0x66, 0xbc, 0x47, 0x4d, 0x03,
	0x4f, 0xdc, 0x48, 0x9b, 0x79, 0xc7, 0x94, 0xc1, 0x34, 0x77, 0x49, 0x5e, 0xa6, 0xb8, 0xe3, 0x7d,
	0xd2, 0x47, 0x81, 0xbb, 0xf5, 0x94, 0x9f, 0x6a, 0x9d, 0x74, 0xc8, 0x07, 0x93, 0xce, 0xec, 0x58,
	0x04, 0xc0, 0xde, 0xc0, 0x7f, 0xca, 0xa0, 0x74, 0x98, 0x26, 0xce, 0xc8, 0xd2, 0x4a, 0xe5, 0xbc,
	0x27, 0x43, 0xea, 0x67, 0xb5, 0xb4, 0x38, 0x28, 0xec, 0x15, 0x9c, 0xa9, 0xda, 0xf8, 0xa4, 0x71,
	0x10, 0xc8, 0xc1, 0xd3, 0x86, 0xff, 0x1a, 0x68, 0xf6, 0x0e, 0x46, 0x55, 0xfb, 0xf2, 0x96, 0x8f,
	0x26, 0xdd, 0xd9, 0xe8, 0x8a, 0x5d, 0x86, 0xfc, 0x5d, 0x1e, 0x42, 0x21, 0xfe, 0x2e, 0x63, 0x57,
	0x30, 0xc8, 0x4b, 0x87, 0x2b, 0x23, 0x0b, 0x1e, 0x53, 0xcb, 0x45, 0xd3, 0x32, 0xaf, 0xff, 0x9d,
	0xa0, 0x8a, 0xb6, 0x8e, 0xbd, 0x87, 0x71, 0xa6, 0x8b, 0x34, 0x69, 0x2e, 0xe0, 0x63, 0x6a, 0xe4,
	0x6d, 0x63, 0xcd, 0xb7, 0xad, 0xb1, 0x2f, 0x6f, 0x03, 0xf4, 0x18, 0x06, 0x6e, 0x97, 0xd0, 0x93,
	0xf3, 0x13, 0xf2, 0xbc, 0xef, 0x76, 0x73, 0x4a, 0x00, 0x49, 0xb5, 0xe9, 0xa7, 0xe1, 0xa1, 0xdd,
	0x2e, 0x78, 0xce, 0x20, 0xc2, 0x6d, 0x5e, 0xf0, 0x33, 0xea, 0xa0, 0xbf, 0xa7, 0x3f, 0xe1, 0xec,
	0xfe, 0xae, 0xfb, 0x21, 0x1a, 0x1e, 0x42, 0xf4, 0x12, 0x4e, 0x1a, 0xf3, 0x33, 0xcc, 0x57, 0x99,
	0xa3, 0x2c, 0x45, 0x62, 0x5c, 0xb3, 0x37, 0x44, 0xb2, 0xd7, 0x70, 0xde, 0x5a, 0xde, 0xde, 0x19,
	0x72, 0xd5, 0x7a, 0xbe, 0x08, 0xf7, 0x4e, 0x7f, 0x75, 0xe0, 0xe4, 0x5f, 0x9b, 0xd8, 0x23, 0xe8,
	0x3b, 0x34, 0xeb, 0x24, 0x4f, 0x69, 0x7f, 0x24, 0x7a, 0x1e, 0xde, 0xa6, 0xfe, 0x93, 0x2e, 0xb5,
	0x59, 0xcb, 0xa2, 0x5e, 0x5b, 0x23, 0xf6, 0x04, 0x06, 0xad, 0x91, 0x5d, 0x52, 0x5a, 0xec, 0x35,
	0x87, 0xeb, 0xaa, 0xf0, 0x41, 0x8a, 0x82, 0xd6, 0x60, 0xbf, 0x28, 0xd5, 0x09, 0x79, 0x12, 0x92,
	0xdb, 0x4b, 0xf5, 0xc7, 0x6d, 0x5e, 0xf8, 0x8f, 0x5e, 0xe9, 0xa2, 0x40, 0xe5, 0x92, 0x65, 0xa1,
	0xd5, 0x77, 0x8a, 0x6f, 0x24, 0xe2, 0x9a, 0xfc, 0xe0, 0xb9, 0x65, 0x8f, 0x7e, 0x9e, 0xde, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x63, 0x0c, 0x5e, 0xaf, 0x04, 0x00, 0x00,
}
