// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	pb "gt.pro/gtio/go-gt/dag/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type File struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              []byte        `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	BindKey              string        `protobuf:"bytes,3,opt,name=bind_key,json=bindKey,proto3" json:"bind_key,omitempty"`
	Size_                uint64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	State                *StorageState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *File) GetBindKey() string {
	if m != nil {
		return m.BindKey
	}
	return ""
}

func (m *File) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *File) GetState() *StorageState {
	if m != nil {
		return m.State
	}
	return nil
}

type StorageState struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Result               []byte   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,3,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageState) Reset()         { *m = StorageState{} }
func (m *StorageState) String() string { return proto.CompactTextString(m) }
func (*StorageState) ProtoMessage()    {}
func (*StorageState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}
func (m *StorageState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageState.Unmarshal(m, b)
}
func (m *StorageState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageState.Marshal(b, m, deterministic)
}
func (m *StorageState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageState.Merge(m, src)
}
func (m *StorageState) XXX_Size() int {
	return xxx_messageInfo_StorageState.Size(m)
}
func (m *StorageState) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageState.DiscardUnknown(m)
}

var xxx_messageInfo_StorageState proto.InternalMessageInfo

func (m *StorageState) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *StorageState) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *StorageState) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type ComplexData struct {
	Flies                []*File  `protobuf:"bytes,1,rep,name=flies,proto3" json:"flies,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplexData) Reset()         { *m = ComplexData{} }
func (m *ComplexData) String() string { return proto.CompactTextString(m) }
func (*ComplexData) ProtoMessage()    {}
func (*ComplexData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{3}
}
func (m *ComplexData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexData.Unmarshal(m, b)
}
func (m *ComplexData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexData.Marshal(b, m, deterministic)
}
func (m *ComplexData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexData.Merge(m, src)
}
func (m *ComplexData) XXX_Size() int {
	return xxx_messageInfo_ComplexData.Size(m)
}
func (m *ComplexData) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexData.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexData proto.InternalMessageInfo

func (m *ComplexData) GetFlies() []*File {
	if m != nil {
		return m.Flies
	}
	return nil
}

func (m *ComplexData) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Signature struct {
	Signer               []byte   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{4}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *Signature) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                []byte     `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Nonce                uint64     `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId              uint32     `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp            int64      `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 *Data      `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Priority             uint32     `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	GasLimit             []byte     `protobuf:"bytes,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Sign                 *Signature `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	Memo                 []byte     `protobuf:"bytes,12,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Transaction) GetMemo() []byte {
	if m != nil {
		return m.Memo
	}
	return nil
}

type PsecData struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PsecData) Reset()         { *m = PsecData{} }
func (m *PsecData) String() string { return proto.CompactTextString(m) }
func (*PsecData) ProtoMessage()    {}
func (*PsecData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{6}
}
func (m *PsecData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PsecData.Unmarshal(m, b)
}
func (m *PsecData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PsecData.Marshal(b, m, deterministic)
}
func (m *PsecData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PsecData.Merge(m, src)
}
func (m *PsecData) XXX_Size() int {
	return xxx_messageInfo_PsecData.Size(m)
}
func (m *PsecData) XXX_DiscardUnknown() {
	xxx_messageInfo_PsecData.DiscardUnknown(m)
}

var xxx_messageInfo_PsecData proto.InternalMessageInfo

func (m *PsecData) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *PsecData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockHeader struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte     `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase             []byte     `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Timestamp            int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId              uint32     `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height               uint64     `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	TermId               uint64     `protobuf:"varint,7,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	StateRoot            []byte     `protobuf:"bytes,8,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxsRoot              []byte     `protobuf:"bytes,9,opt,name=txs_root,json=txsRoot,proto3" json:"txs_root,omitempty"`
	EventsRoot           []byte     `protobuf:"bytes,10,opt,name=events_root,json=eventsRoot,proto3" json:"events_root,omitempty"`
	ConsensusRoot        []byte     `protobuf:"bytes,11,opt,name=consensus_root,json=consensusRoot,proto3" json:"consensus_root,omitempty"`
	Memo                 *BlockMemo `protobuf:"bytes,12,opt,name=memo,proto3" json:"memo,omitempty"`
	Output               []byte     `protobuf:"bytes,13,opt,name=output,proto3" json:"output,omitempty"`
	Sign                 *Signature `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`
	Random               *Random    `protobuf:"bytes,15,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{7}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTermId() uint64 {
	if m != nil {
		return m.TermId
	}
	return 0
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTxsRoot() []byte {
	if m != nil {
		return m.TxsRoot
	}
	return nil
}

func (m *BlockHeader) GetEventsRoot() []byte {
	if m != nil {
		return m.EventsRoot
	}
	return nil
}

func (m *BlockHeader) GetConsensusRoot() []byte {
	if m != nil {
		return m.ConsensusRoot
	}
	return nil
}

func (m *BlockHeader) GetMemo() *BlockMemo {
	if m != nil {
		return m.Memo
	}
	return nil
}

func (m *BlockHeader) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *BlockHeader) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *BlockHeader) GetRandom() *Random {
	if m != nil {
		return m.Random
	}
	return nil
}

type BlockMemo struct {
	Rewards              []*BlockFundEntity `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	Pledge               []*BlockFundEntity `protobuf:"bytes,2,rep,name=pledge,proto3" json:"pledge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockMemo) Reset()         { *m = BlockMemo{} }
func (m *BlockMemo) String() string { return proto.CompactTextString(m) }
func (*BlockMemo) ProtoMessage()    {}
func (*BlockMemo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{8}
}
func (m *BlockMemo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMemo.Unmarshal(m, b)
}
func (m *BlockMemo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMemo.Marshal(b, m, deterministic)
}
func (m *BlockMemo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMemo.Merge(m, src)
}
func (m *BlockMemo) XXX_Size() int {
	return xxx_messageInfo_BlockMemo.Size(m)
}
func (m *BlockMemo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMemo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMemo proto.InternalMessageInfo

func (m *BlockMemo) GetRewards() []*BlockFundEntity {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *BlockMemo) GetPledge() []*BlockFundEntity {
	if m != nil {
		return m.Pledge
	}
	return nil
}

type BlockFundEntity struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenFund           []byte   `protobuf:"bytes,3,opt,name=frozen_fund,json=frozenFund,proto3" json:"frozen_fund,omitempty"`
	PledgeFund           []byte   `protobuf:"bytes,4,opt,name=pledge_fund,json=pledgeFund,proto3" json:"pledge_fund,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockFundEntity) Reset()         { *m = BlockFundEntity{} }
func (m *BlockFundEntity) String() string { return proto.CompactTextString(m) }
func (*BlockFundEntity) ProtoMessage()    {}
func (*BlockFundEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{9}
}
func (m *BlockFundEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockFundEntity.Unmarshal(m, b)
}
func (m *BlockFundEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockFundEntity.Marshal(b, m, deterministic)
}
func (m *BlockFundEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockFundEntity.Merge(m, src)
}
func (m *BlockFundEntity) XXX_Size() int {
	return xxx_messageInfo_BlockFundEntity.Size(m)
}
func (m *BlockFundEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockFundEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BlockFundEntity proto.InternalMessageInfo

func (m *BlockFundEntity) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BlockFundEntity) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *BlockFundEntity) GetFrozenFund() []byte {
	if m != nil {
		return m.FrozenFund
	}
	return nil
}

func (m *BlockFundEntity) GetPledgeFund() []byte {
	if m != nil {
		return m.PledgeFund
	}
	return nil
}

type Block struct {
	Hash                 []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header               *BlockHeader   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []*Transaction `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	Dependency           *pb.Dag        `protobuf:"bytes,4,opt,name=dependency,proto3" json:"dependency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{10}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() []*Transaction {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Block) GetDependency() *pb.Dag {
	if m != nil {
		return m.Dependency
	}
	return nil
}

type DownloadBlock struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sign                 *Signature `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DownloadBlock) Reset()         { *m = DownloadBlock{} }
func (m *DownloadBlock) String() string { return proto.CompactTextString(m) }
func (*DownloadBlock) ProtoMessage()    {}
func (*DownloadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{11}
}
func (m *DownloadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadBlock.Unmarshal(m, b)
}
func (m *DownloadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadBlock.Marshal(b, m, deterministic)
}
func (m *DownloadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadBlock.Merge(m, src)
}
func (m *DownloadBlock) XXX_Size() int {
	return xxx_messageInfo_DownloadBlock.Size(m)
}
func (m *DownloadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadBlock proto.InternalMessageInfo

func (m *DownloadBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DownloadBlock) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Promise struct {
	ProposalId           uint64     `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	MaxAcceptedPropose   *Propose   `protobuf:"bytes,2,opt,name=max_accepted_propose,json=maxAcceptedPropose,proto3" json:"max_accepted_propose,omitempty"`
	Sign                 *Signature `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Promise) Reset()         { *m = Promise{} }
func (m *Promise) String() string { return proto.CompactTextString(m) }
func (*Promise) ProtoMessage()    {}
func (*Promise) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{12}
}
func (m *Promise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promise.Unmarshal(m, b)
}
func (m *Promise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promise.Marshal(b, m, deterministic)
}
func (m *Promise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promise.Merge(m, src)
}
func (m *Promise) XXX_Size() int {
	return xxx_messageInfo_Promise.Size(m)
}
func (m *Promise) XXX_DiscardUnknown() {
	xxx_messageInfo_Promise.DiscardUnknown(m)
}

var xxx_messageInfo_Promise proto.InternalMessageInfo

func (m *Promise) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *Promise) GetMaxAcceptedPropose() *Propose {
	if m != nil {
		return m.MaxAcceptedPropose
	}
	return nil
}

func (m *Promise) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Propose struct {
	Num                  uint64     `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sign                 *Signature `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Propose) Reset()         { *m = Propose{} }
func (m *Propose) String() string { return proto.CompactTextString(m) }
func (*Propose) ProtoMessage()    {}
func (*Propose) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{13}
}
func (m *Propose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propose.Unmarshal(m, b)
}
func (m *Propose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propose.Marshal(b, m, deterministic)
}
func (m *Propose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propose.Merge(m, src)
}
func (m *Propose) XXX_Size() int {
	return xxx_messageInfo_Propose.Size(m)
}
func (m *Propose) XXX_DiscardUnknown() {
	xxx_messageInfo_Propose.DiscardUnknown(m)
}

var xxx_messageInfo_Propose proto.InternalMessageInfo

func (m *Propose) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Propose) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Propose) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type PbftMsg struct {
	Type                 uint32     `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ViewId               string     `protobuf:"bytes,2,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	SeqId                uint64     `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Timestamp            int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte     `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Sign                 *Signature `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PbftMsg) Reset()         { *m = PbftMsg{} }
func (m *PbftMsg) String() string { return proto.CompactTextString(m) }
func (*PbftMsg) ProtoMessage()    {}
func (*PbftMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{14}
}
func (m *PbftMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbftMsg.Unmarshal(m, b)
}
func (m *PbftMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbftMsg.Marshal(b, m, deterministic)
}
func (m *PbftMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbftMsg.Merge(m, src)
}
func (m *PbftMsg) XXX_Size() int {
	return xxx_messageInfo_PbftMsg.Size(m)
}
func (m *PbftMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PbftMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PbftMsg proto.InternalMessageInfo

func (m *PbftMsg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PbftMsg) GetViewId() string {
	if m != nil {
		return m.ViewId
	}
	return ""
}

func (m *PbftMsg) GetSeqId() uint64 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func (m *PbftMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PbftMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PbftMsg) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SystemConfig struct {
	BlockInterval           int32    `protobuf:"varint,1,opt,name=block_interval,json=blockInterval,proto3" json:"block_interval,omitempty"`
	SuperNodeCount          int32    `protobuf:"varint,2,opt,name=super_node_count,json=superNodeCount,proto3" json:"super_node_count,omitempty"`
	WitnessCount            int32    `protobuf:"varint,3,opt,name=witness_count,json=witnessCount,proto3" json:"witness_count,omitempty"`
	SuperNodes              []*Node  `protobuf:"bytes,4,rep,name=super_nodes,json=superNodes,proto3" json:"super_nodes,omitempty"`
	ContractTxFee           []byte   `protobuf:"bytes,5,opt,name=contract_tx_fee,json=contractTxFee,proto3" json:"contract_tx_fee,omitempty"`
	DeployContractMinVolume int32    `protobuf:"varint,6,opt,name=deploy_contract_min_volume,json=deployContractMinVolume,proto3" json:"deploy_contract_min_volume,omitempty"`
	FloatingCycle           int32    `protobuf:"varint,7,opt,name=floating_cycle,json=floatingCycle,proto3" json:"floating_cycle,omitempty"`
	MinPledge               []byte   `protobuf:"bytes,8,opt,name=min_pledge,json=minPledge,proto3" json:"min_pledge,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SystemConfig) Reset()         { *m = SystemConfig{} }
func (m *SystemConfig) String() string { return proto.CompactTextString(m) }
func (*SystemConfig) ProtoMessage()    {}
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{15}
}
func (m *SystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemConfig.Unmarshal(m, b)
}
func (m *SystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemConfig.Marshal(b, m, deterministic)
}
func (m *SystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemConfig.Merge(m, src)
}
func (m *SystemConfig) XXX_Size() int {
	return xxx_messageInfo_SystemConfig.Size(m)
}
func (m *SystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SystemConfig proto.InternalMessageInfo

func (m *SystemConfig) GetBlockInterval() int32 {
	if m != nil {
		return m.BlockInterval
	}
	return 0
}

func (m *SystemConfig) GetSuperNodeCount() int32 {
	if m != nil {
		return m.SuperNodeCount
	}
	return 0
}

func (m *SystemConfig) GetWitnessCount() int32 {
	if m != nil {
		return m.WitnessCount
	}
	return 0
}

func (m *SystemConfig) GetSuperNodes() []*Node {
	if m != nil {
		return m.SuperNodes
	}
	return nil
}

func (m *SystemConfig) GetContractTxFee() []byte {
	if m != nil {
		return m.ContractTxFee
	}
	return nil
}

func (m *SystemConfig) GetDeployContractMinVolume() int32 {
	if m != nil {
		return m.DeployContractMinVolume
	}
	return 0
}

func (m *SystemConfig) GetFloatingCycle() int32 {
	if m != nil {
		return m.FloatingCycle
	}
	return 0
}

func (m *SystemConfig) GetMinPledge() []byte {
	if m != nil {
		return m.MinPledge
	}
	return nil
}

type Node struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Fund                 []byte   `protobuf:"bytes,2,opt,name=fund,proto3" json:"fund,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{16}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetFund() []byte {
	if m != nil {
		return m.Fund
	}
	return nil
}

type Random struct {
	VrfSeed              []byte   `protobuf:"bytes,1,opt,name=vrf_seed,json=vrfSeed,proto3" json:"vrf_seed,omitempty"`
	VrfProof             []byte   `protobuf:"bytes,2,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Random) Reset()         { *m = Random{} }
func (m *Random) String() string { return proto.CompactTextString(m) }
func (*Random) ProtoMessage()    {}
func (*Random) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{17}
}
func (m *Random) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Random.Unmarshal(m, b)
}
func (m *Random) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Random.Marshal(b, m, deterministic)
}
func (m *Random) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Random.Merge(m, src)
}
func (m *Random) XXX_Size() int {
	return xxx_messageInfo_Random.Size(m)
}
func (m *Random) XXX_DiscardUnknown() {
	xxx_messageInfo_Random.DiscardUnknown(m)
}

var xxx_messageInfo_Random proto.InternalMessageInfo

func (m *Random) GetVrfSeed() []byte {
	if m != nil {
		return m.VrfSeed
	}
	return nil
}

func (m *Random) GetVrfProof() []byte {
	if m != nil {
		return m.VrfProof
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "corepb.Data")
	proto.RegisterType((*File)(nil), "corepb.File")
	proto.RegisterType((*StorageState)(nil), "corepb.StorageState")
	proto.RegisterType((*ComplexData)(nil), "corepb.ComplexData")
	proto.RegisterType((*Signature)(nil), "corepb.Signature")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*PsecData)(nil), "corepb.PsecData")
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
	proto.RegisterType((*BlockMemo)(nil), "corepb.BlockMemo")
	proto.RegisterType((*BlockFundEntity)(nil), "corepb.BlockFundEntity")
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*DownloadBlock)(nil), "corepb.DownloadBlock")
	proto.RegisterType((*Promise)(nil), "corepb.Promise")
	proto.RegisterType((*Propose)(nil), "corepb.Propose")
	proto.RegisterType((*PbftMsg)(nil), "corepb.PbftMsg")
	proto.RegisterType((*SystemConfig)(nil), "corepb.SystemConfig")
	proto.RegisterType((*Node)(nil), "corepb.Node")
	proto.RegisterType((*Random)(nil), "corepb.Random")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 1264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4d, 0x6f, 0x1c, 0x45,
	0x13, 0xd6, 0x7e, 0x7b, 0x6b, 0x77, 0xed, 0xbc, 0xfd, 0xe6, 0x8d, 0xe7, 0x35, 0xa0, 0xac, 0x16,
	0x25, 0xac, 0x02, 0xb1, 0x45, 0x40, 0xe2, 0x00, 0x07, 0x82, 0x43, 0x14, 0x03, 0x41, 0x56, 0x3b,
	0x42, 0x70, 0x1a, 0xf5, 0x4e, 0xd7, 0x8e, 0x47, 0x99, 0xe9, 0x9e, 0x4c, 0xf7, 0xda, 0xbb, 0xf9,
	0x03, 0x1c, 0xb9, 0x70, 0xe5, 0xca, 0xef, 0xe0, 0x67, 0x70, 0xe2, 0xb7, 0xa0, 0xea, 0xee, 0x19,
	0x7f, 0x84, 0x58, 0x9c, 0xb6, 0xeb, 0xa9, 0xa7, 0x6b, 0xab, 0xab, 0xaa, 0x9f, 0x1e, 0x18, 0x2d,
	0x72, 0x9d, 0xbc, 0xdc, 0x2f, 0x2b, 0x6d, 0x35, 0xeb, 0x27, 0xba, 0xc2, 0x72, 0xb1, 0x37, 0x4b,
	0x2d, 0x21, 0x07, 0xa9, 0xcd, 0xf4, 0x41, 0xaa, 0x1f, 0xa6, 0xf6, 0x40, 0x8a, 0xf4, 0xa0, 0x5c,
	0xd0, 0x8f, 0xe7, 0xce, 0x3e, 0x82, 0xee, 0x13, 0x61, 0x05, 0x63, 0xd0, 0xb5, 0x9b, 0x12, 0xa3,
	0xd6, 0xb4, 0x35, 0x1f, 0x72, 0xb7, 0x66, 0xb7, 0xa0, 0x53, 0x98, 0x34, 0x6a, 0x4f, 0x5b, 0xf3,
	0x31, 0xa7, 0xe5, 0xec, 0x97, 0x16, 0x74, 0x9f, 0x66, 0x39, 0x12, 0x5d, 0x89, 0xa2, 0xa1, 0xd3,
	0x9a, 0x45, 0x30, 0x48, 0xb4, 0xb2, 0xa8, 0x6c, 0xd8, 0x52, 0x9b, 0xec, 0xff, 0xb0, 0xb5, 0xc8,
	0x94, 0x8c, 0x5f, 0xe2, 0x26, 0xea, 0xb8, 0x1d, 0x03, 0xb2, 0xbf, 0xc5, 0x0d, 0x05, 0x32, 0xd9,
	0x6b, 0x8c, 0xba, 0xd3, 0xd6, 0xbc, 0xcb, 0xdd, 0x9a, 0x3d, 0x80, 0x9e, 0xb1, 0xc2, 0x62, 0xd4,
	0x9b, 0xb6, 0xe6, 0xa3, 0x47, 0xb7, 0xf7, 0xfd, 0x79, 0xf6, 0x4f, 0xac, 0xae, 0x44, 0x8a, 0x27,
	0xe4, 0xe3, 0x9e, 0x32, 0xfb, 0x09, 0xc6, 0x97, 0x61, 0x8a, 0x57, 0x68, 0xd9, 0x24, 0x46, 0x6b,
	0x76, 0x07, 0xfa, 0x15, 0x9a, 0x55, 0x5e, 0xe7, 0x15, 0x2c, 0xf6, 0x1e, 0x00, 0xae, 0x6d, 0x25,
	0x62, 0x29, 0xac, 0x70, 0x89, 0x8d, 0xf9, 0xd0, 0x21, 0x54, 0x92, 0xd9, 0x09, 0x8c, 0x0e, 0x75,
	0x51, 0xe6, 0xb8, 0x76, 0x15, 0x9a, 0x41, 0x6f, 0x99, 0x67, 0x68, 0xa2, 0xd6, 0xb4, 0x33, 0x1f,
	0x3d, 0x1a, 0xd7, 0x59, 0x51, 0x3d, 0xb8, 0x77, 0xb1, 0x29, 0x74, 0x5d, 0xac, 0xb6, 0x4b, 0xbc,
	0xa1, 0xd0, 0x7e, 0xee, 0x3c, 0xb3, 0xcf, 0x60, 0x78, 0x92, 0xa5, 0x4a, 0xd8, 0x55, 0xe5, 0x12,
	0x33, 0x59, 0xaa, 0xb0, 0x72, 0xe9, 0x8e, 0x79, 0xb0, 0xe8, 0x10, 0x4d, 0x98, 0x71, 0xd8, 0xf8,
	0x47, 0x1b, 0x46, 0x2f, 0x2a, 0xa1, 0x8c, 0x48, 0x6c, 0xa6, 0x15, 0x71, 0x4e, 0x85, 0x39, 0x0d,
	0x3b, 0xdd, 0x9a, 0xb0, 0x65, 0xa5, 0x8b, 0x7a, 0x1f, 0xad, 0xd9, 0x36, 0xb4, 0xad, 0x0e, 0x87,
	0x6b, 0x5b, 0xcd, 0x6e, 0x43, 0xef, 0x4c, 0xe4, 0x2b, 0x5f, 0xf1, 0x31, 0xf7, 0x06, 0xa1, 0x4a,
	0xab, 0xc4, 0x97, 0xbc, 0xcb, 0xbd, 0x41, 0x7d, 0x4b, 0x4e, 0x45, 0xa6, 0xe2, 0x4c, 0x46, 0xfd,
	0x69, 0x6b, 0x3e, 0xe1, 0x03, 0x67, 0x1f, 0x49, 0xf6, 0x2e, 0x0c, 0x6d, 0x56, 0xa0, 0xb1, 0xa2,
	0x28, 0xa3, 0xc1, 0xb4, 0x35, 0xef, 0xf0, 0x0b, 0xa0, 0xa9, 0xc3, 0xd6, 0xdb, 0xea, 0xc0, 0xf6,
	0x60, 0xab, 0xac, 0x32, 0x5d, 0x65, 0x76, 0x13, 0x0d, 0x5d, 0xe8, 0xc6, 0x66, 0xef, 0xc0, 0x30,
	0x15, 0x26, 0xce, 0xb3, 0x22, 0xb3, 0x11, 0xb8, 0x34, 0xb7, 0x52, 0x61, 0xbe, 0x23, 0x9b, 0xdd,
	0xa3, 0x81, 0x49, 0x55, 0x34, 0x72, 0xa1, 0xff, 0xd3, 0xcc, 0x46, 0x5d, 0x54, 0xee, 0xdc, 0x6e,
	0x0e, 0xb0, 0xd0, 0xd1, 0xd8, 0x97, 0x82, 0xd6, 0xb3, 0x2f, 0x60, 0xeb, 0xd8, 0x60, 0xd2, 0xcc,
	0x3b, 0x56, 0x85, 0x2b, 0x5f, 0x87, 0xbb, 0xf5, 0xd5, 0x33, 0xb5, 0xaf, 0x9d, 0x69, 0xf6, 0x67,
	0x07, 0x46, 0x5f, 0xd1, 0x2d, 0x7b, 0x86, 0x42, 0xfa, 0x26, 0xbd, 0xd1, 0x80, 0xbb, 0x30, 0x2a,
	0x45, 0x85, 0xca, 0xc6, 0xce, 0xe5, 0xfb, 0x00, 0x1e, 0x7a, 0x46, 0x84, 0x3d, 0xd8, 0x4a, 0x74,
	0xa6, 0x16, 0xc2, 0x60, 0xe8, 0x49, 0x63, 0x5f, 0xfd, 0xfb, 0xee, 0xf5, 0x92, 0x5e, 0xee, 0x45,
	0xef, 0x6a, 0x2f, 0xee, 0x40, 0xff, 0x14, 0xb3, 0xf4, 0xd4, 0xba, 0x26, 0x75, 0x79, 0xb0, 0xd8,
	0x2e, 0x0c, 0xe8, 0x5c, 0xb4, 0x63, 0xe0, 0x1d, 0x64, 0x1e, 0x49, 0x1a, 0x7c, 0x77, 0x7b, 0xe2,
	0x4a, 0x6b, 0xeb, 0x9a, 0x34, 0xe6, 0x43, 0x87, 0x70, 0xad, 0xdd, 0x75, 0xb5, 0x6b, 0xe3, 0x9d,
	0x43, 0x7f, 0x93, 0xed, 0xda, 0x38, 0xd7, 0x5d, 0x18, 0xe1, 0x19, 0x2a, 0x1b, 0xbc, 0xbe, 0x39,
	0xe0, 0x21, 0x47, 0xb8, 0x07, 0xdb, 0x89, 0x56, 0x06, 0x95, 0x59, 0x05, 0xce, 0xc8, 0x71, 0x26,
	0x0d, 0x1a, 0x68, 0x17, 0xed, 0xb9, 0xd4, 0x45, 0x57, 0xdf, 0xe7, 0x58, 0x68, 0xdf, 0x31, 0x3a,
	0x99, 0x5e, 0xd9, 0x72, 0x65, 0xa3, 0x89, 0xbf, 0x20, 0xde, 0x6a, 0x86, 0x60, 0xfb, 0xe6, 0x21,
	0xb8, 0x0f, 0xfd, 0x4a, 0x28, 0xa9, 0x8b, 0x68, 0xc7, 0x11, 0xb7, 0x6b, 0x22, 0x77, 0x28, 0x0f,
	0xde, 0x99, 0x86, 0x61, 0xf3, 0xcf, 0xec, 0x63, 0x18, 0x54, 0x78, 0x2e, 0x2a, 0x59, 0xdf, 0xf4,
	0xdd, 0x2b, 0xd9, 0x3d, 0x5d, 0x29, 0xf9, 0xb5, 0xb2, 0x99, 0xdd, 0xf0, 0x9a, 0xc7, 0x0e, 0xa0,
	0x5f, 0xe6, 0x28, 0x53, 0x8c, 0xda, 0x37, 0xef, 0x08, 0xb4, 0xd9, 0xcf, 0x2d, 0xd8, 0xb9, 0xe6,
	0x23, 0xf9, 0x14, 0x52, 0x56, 0x68, 0x4c, 0x18, 0xa9, 0xda, 0x24, 0xcf, 0x42, 0xe4, 0x82, 0xae,
	0x67, 0x10, 0xd6, 0x60, 0x52, 0x3b, 0x96, 0x95, 0x7e, 0x8d, 0x2a, 0x5e, 0xae, 0x94, 0x0c, 0x13,
	0x05, 0x1e, 0xa2, 0xd0, 0x6e, 0x20, 0xdd, 0x5f, 0x7a, 0x42, 0x37, 0x0c, 0xa4, 0x83, 0x88, 0x30,
	0xfb, 0xad, 0x05, 0x3d, 0x97, 0xc9, 0x3f, 0xce, 0xf3, 0x87, 0x34, 0x59, 0x34, 0xed, 0x41, 0xd1,
	0xfe, 0x7b, 0xe5, 0x60, 0xfe, 0x22, 0xf0, 0x40, 0x61, 0x1f, 0x40, 0x77, 0xa1, 0x25, 0x29, 0x7c,
	0xe7, 0x32, 0xf5, 0x92, 0x68, 0x71, 0x47, 0x60, 0x0f, 0x00, 0x24, 0x96, 0xa8, 0x24, 0xaa, 0x64,
	0xe3, 0x72, 0x1a, 0x3d, 0x82, 0x7d, 0x29, 0x52, 0x27, 0x11, 0x29, 0xbf, 0xe4, 0x9d, 0x7d, 0x03,
	0x93, 0x27, 0xfa, 0x5c, 0xe5, 0x5a, 0xc8, 0xb7, 0xa7, 0x59, 0x8f, 0x43, 0xfb, 0xc6, 0x71, 0x98,
	0xfd, 0xda, 0x82, 0xc1, 0x71, 0xa5, 0x8b, 0xcc, 0xb8, 0xca, 0x95, 0x95, 0x2e, 0xb5, 0x11, 0x39,
	0xdd, 0x8f, 0x96, 0xbb, 0x1f, 0x50, 0x43, 0x47, 0x92, 0x3d, 0x86, 0xdb, 0x85, 0x58, 0xc7, 0x22,
	0x49, 0xb0, 0xb4, 0x28, 0x63, 0xef, 0xc2, 0xf0, 0x1f, 0x3b, 0xf5, 0x7f, 0x1c, 0x7b, 0x98, 0xb3,
	0x42, 0xac, 0x1f, 0x07, 0x6e, 0xc0, 0x9a, 0xb4, 0x3a, 0x37, 0xa7, 0xf5, 0xa3, 0xcb, 0xca, 0xed,
	0xb8, 0x05, 0x1d, 0xb5, 0x2a, 0x42, 0x36, 0xb4, 0xbc, 0x90, 0xeb, 0xf6, 0x65, 0xb9, 0xfe, 0x97,
	0x91, 0x7f, 0xa7, 0x03, 0x2f, 0x96, 0xf6, 0xb9, 0x49, 0xaf, 0x3c, 0xf0, 0x93, 0xf0, 0xc0, 0xef,
	0xc2, 0xe0, 0x2c, 0xc3, 0x73, 0x2a, 0x40, 0xdb, 0xbd, 0x97, 0x7d, 0x32, 0x8f, 0x24, 0xfb, 0x1f,
	0xf4, 0x0d, 0xbe, 0x22, 0xbc, 0xe3, 0xdf, 0x03, 0x83, 0xaf, 0xae, 0x8b, 0xfe, 0x1b, 0x0a, 0x55,
	0xbf, 0x5a, 0xbd, 0x8b, 0x57, 0xab, 0x49, 0xb4, 0x7f, 0x73, 0xa2, 0x7f, 0xb5, 0x61, 0x7c, 0xb2,
	0x31, 0x16, 0x8b, 0x43, 0xad, 0x96, 0x59, 0x4a, 0x32, 0xe2, 0xbe, 0x68, 0xe2, 0x4c, 0x59, 0xac,
	0xce, 0x44, 0xee, 0xf2, 0xee, 0xf1, 0x89, 0x43, 0x8f, 0x02, 0xc8, 0xe6, 0x70, 0xcb, 0xac, 0x4a,
	0xac, 0x62, 0xa5, 0x25, 0xc6, 0x89, 0x5e, 0x85, 0x6f, 0x8f, 0x1e, 0xdf, 0x76, 0xf8, 0xf7, 0x5a,
	0xe2, 0x21, 0xa1, 0xec, 0x7d, 0x98, 0x9c, 0x67, 0x56, 0xa1, 0x31, 0x81, 0xd6, 0x71, 0xb4, 0x71,
	0x00, 0x3d, 0xe9, 0x21, 0x8c, 0x2e, 0xc2, 0x99, 0xa8, 0x7b, 0xf5, 0xa1, 0xa7, 0x60, 0x1c, 0x9a,
	0xb8, 0x86, 0xdd, 0x87, 0x1d, 0xfa, 0xc2, 0xa9, 0x44, 0x62, 0x63, 0xbb, 0x8e, 0x97, 0x88, 0xe1,
	0xec, 0x93, 0x1a, 0x7e, 0xb1, 0x7e, 0x8a, 0xc8, 0x3e, 0x87, 0x3d, 0x89, 0x65, 0xae, 0x37, 0x71,
	0x43, 0x2f, 0x32, 0x15, 0x9f, 0xe9, 0x7c, 0x55, 0xa0, 0x2b, 0x4d, 0x8f, 0xef, 0x7a, 0xc6, 0x61,
	0x20, 0x3c, 0xcf, 0xd4, 0x0f, 0xce, 0x4d, 0x95, 0x58, 0xe6, 0x5a, 0xd8, 0x4c, 0xa5, 0x71, 0xb2,
	0x49, 0x72, 0x74, 0x5a, 0xde, 0xe3, 0x93, 0x1a, 0x3d, 0x24, 0x90, 0x24, 0x9d, 0x62, 0x06, 0x19,
	0x0a, 0x92, 0x5e, 0x64, 0xea, 0xd8, 0x0b, 0xce, 0xa7, 0xd0, 0xa5, 0x9c, 0xaf, 0x8b, 0xcc, 0xf0,
	0x42, 0x64, 0xe8, 0xdb, 0x81, 0x24, 0xa2, 0xfe, 0x76, 0x20, 0x71, 0xf8, 0x12, 0xfa, 0x5e, 0x29,
	0xe9, 0x49, 0x38, 0xab, 0x96, 0xb1, 0x41, 0x94, 0xb5, 0x3a, 0x9d, 0x55, 0xcb, 0x13, 0x44, 0x49,
	0xaf, 0x35, 0xb9, 0xca, 0x4a, 0xeb, 0x65, 0xd8, 0x4d, 0xdc, 0x63, 0xb2, 0x17, 0x7d, 0xf7, 0x95,
	0xf9, 0xc9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xcb, 0xb0, 0x27, 0xa0, 0x0a, 0x00, 0x00,
}
