// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: state.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Council struct {
	Meta                 *CouncilMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Panels               []*Panel     `protobuf:"bytes,2,rep,name=panels,proto3" json:"panels,omitempty"`
	State                *PeriodState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Council) Reset()         { *m = Council{} }
func (m *Council) String() string { return proto.CompactTextString(m) }
func (*Council) ProtoMessage()    {}
func (*Council) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{0}
}
func (m *Council) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Council.Unmarshal(m, b)
}
func (m *Council) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Council.Marshal(b, m, deterministic)
}
func (m *Council) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Council.Merge(m, src)
}
func (m *Council) XXX_Size() int {
	return xxx_messageInfo_Council.Size(m)
}
func (m *Council) XXX_DiscardUnknown() {
	xxx_messageInfo_Council.DiscardUnknown(m)
}

var xxx_messageInfo_Council proto.InternalMessageInfo

func (m *Council) GetMeta() *CouncilMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Council) GetPanels() []*Panel {
	if m != nil {
		return m.Panels
	}
	return nil
}

func (m *Council) GetState() *PeriodState {
	if m != nil {
		return m.State
	}
	return nil
}

type CouncilMeta struct {
	ChainId              uint32        `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TermId               uint64        `protobuf:"varint,2,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	Timestamp            int64         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TenureStartHeight    uint64        `protobuf:"varint,4,opt,name=tenure_start_height,json=tenureStartHeight,proto3" json:"tenure_start_height,omitempty"`
	TenureEndHeight      uint64        `protobuf:"varint,5,opt,name=tenure_end_height,json=tenureEndHeight,proto3" json:"tenure_end_height,omitempty"`
	Config               *SystemConfig `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CouncilMeta) Reset()         { *m = CouncilMeta{} }
func (m *CouncilMeta) String() string { return proto.CompactTextString(m) }
func (*CouncilMeta) ProtoMessage()    {}
func (*CouncilMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{1}
}
func (m *CouncilMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CouncilMeta.Unmarshal(m, b)
}
func (m *CouncilMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CouncilMeta.Marshal(b, m, deterministic)
}
func (m *CouncilMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CouncilMeta.Merge(m, src)
}
func (m *CouncilMeta) XXX_Size() int {
	return xxx_messageInfo_CouncilMeta.Size(m)
}
func (m *CouncilMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CouncilMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CouncilMeta proto.InternalMessageInfo

func (m *CouncilMeta) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *CouncilMeta) GetTermId() uint64 {
	if m != nil {
		return m.TermId
	}
	return 0
}

func (m *CouncilMeta) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CouncilMeta) GetTenureStartHeight() uint64 {
	if m != nil {
		return m.TenureStartHeight
	}
	return 0
}

func (m *CouncilMeta) GetTenureEndHeight() uint64 {
	if m != nil {
		return m.TenureEndHeight
	}
	return 0
}

func (m *CouncilMeta) GetConfig() *SystemConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type PeriodState struct {
	NormalTxCnt          uint64   `protobuf:"varint,1,opt,name=normal_tx_cnt,json=normalTxCnt,proto3" json:"normal_tx_cnt,omitempty"`
	ContractTxCnt        uint64   `protobuf:"varint,2,opt,name=contract_tx_cnt,json=contractTxCnt,proto3" json:"contract_tx_cnt,omitempty"`
	ParticipatorCnt      uint64   `protobuf:"varint,3,opt,name=participator_cnt,json=participatorCnt,proto3" json:"participator_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeriodState) Reset()         { *m = PeriodState{} }
func (m *PeriodState) String() string { return proto.CompactTextString(m) }
func (*PeriodState) ProtoMessage()    {}
func (*PeriodState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{2}
}
func (m *PeriodState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeriodState.Unmarshal(m, b)
}
func (m *PeriodState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeriodState.Marshal(b, m, deterministic)
}
func (m *PeriodState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodState.Merge(m, src)
}
func (m *PeriodState) XXX_Size() int {
	return xxx_messageInfo_PeriodState.Size(m)
}
func (m *PeriodState) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodState.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodState proto.InternalMessageInfo

func (m *PeriodState) GetNormalTxCnt() uint64 {
	if m != nil {
		return m.NormalTxCnt
	}
	return 0
}

func (m *PeriodState) GetContractTxCnt() uint64 {
	if m != nil {
		return m.ContractTxCnt
	}
	return 0
}

func (m *PeriodState) GetParticipatorCnt() uint64 {
	if m != nil {
		return m.ParticipatorCnt
	}
	return 0
}

type Panel struct {
	Leader               *Member   `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Panel) Reset()         { *m = Panel{} }
func (m *Panel) String() string { return proto.CompactTextString(m) }
func (*Panel) ProtoMessage()    {}
func (*Panel) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{3}
}
func (m *Panel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Panel.Unmarshal(m, b)
}
func (m *Panel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Panel.Marshal(b, m, deterministic)
}
func (m *Panel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Panel.Merge(m, src)
}
func (m *Panel) XXX_Size() int {
	return xxx_messageInfo_Panel.Size(m)
}
func (m *Panel) XXX_DiscardUnknown() {
	xxx_messageInfo_Panel.DiscardUnknown(m)
}

var xxx_messageInfo_Panel proto.InternalMessageInfo

func (m *Panel) GetLeader() *Member {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *Panel) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type Member struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PledgeFund           []byte   `protobuf:"bytes,3,opt,name=pledge_fund,json=pledgeFund,proto3" json:"pledge_fund,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{4}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetPledgeFund() []byte {
	if m != nil {
		return m.PledgeFund
	}
	return nil
}

type GenesisCouncil struct {
	Members              []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenesisCouncil) Reset()         { *m = GenesisCouncil{} }
func (m *GenesisCouncil) String() string { return proto.CompactTextString(m) }
func (*GenesisCouncil) ProtoMessage()    {}
func (*GenesisCouncil) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{5}
}
func (m *GenesisCouncil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisCouncil.Unmarshal(m, b)
}
func (m *GenesisCouncil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisCouncil.Marshal(b, m, deterministic)
}
func (m *GenesisCouncil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisCouncil.Merge(m, src)
}
func (m *GenesisCouncil) XXX_Size() int {
	return xxx_messageInfo_GenesisCouncil.Size(m)
}
func (m *GenesisCouncil) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisCouncil.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisCouncil proto.InternalMessageInfo

func (m *GenesisCouncil) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Council)(nil), "corepb.Council")
	proto.RegisterType((*CouncilMeta)(nil), "corepb.CouncilMeta")
	proto.RegisterType((*PeriodState)(nil), "corepb.PeriodState")
	proto.RegisterType((*Panel)(nil), "corepb.Panel")
	proto.RegisterType((*Member)(nil), "corepb.Member")
	proto.RegisterType((*GenesisCouncil)(nil), "corepb.GenesisCouncil")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_a888679467bb7853) }

var fileDescriptor_a888679467bb7853 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0xc9, 0xb6, 0x4d, 0xed, 0x8b, 0xdd, 0xd5, 0x59, 0xc1, 0x28, 0x82, 0x25, 0xb0, 0x6b,
	0x57, 0xb4, 0x85, 0xf5, 0xe6, 0xb5, 0xf8, 0xa3, 0x87, 0x85, 0x65, 0xea, 0x45, 0x10, 0xc2, 0x24,
	0xf3, 0x36, 0x1d, 0x4c, 0x66, 0xc2, 0xe4, 0x15, 0xd6, 0xbb, 0xff, 0xac, 0xff, 0x85, 0x64, 0x26,
	0x83, 0xd5, 0x83, 0xc7, 0xf7, 0xfd, 0x7c, 0x98, 0x79, 0x6f, 0xde, 0x40, 0xd2, 0x91, 0x20, 0x5c,
	0xb5, 0xd6, 0x90, 0x61, 0x71, 0x69, 0x2c, 0xb6, 0xc5, 0xf3, 0x8b, 0x8a, 0xfa, 0x64, 0x5d, 0x91,
	0x32, 0xeb, 0xca, 0xbc, 0xad, 0x68, 0xdd, 0x93, 0x75, 0x5b, 0xac, 0x8b, 0xda, 0x94, 0xdf, 0xbd,
	0x9e, 0xfd, 0x8c, 0x60, 0xba, 0x31, 0x07, 0x5d, 0xaa, 0x9a, 0xbd, 0x82, 0x71, 0x83, 0x24, 0xd2,
	0x68, 0x11, 0x2d, 0x93, 0xeb, 0xf3, 0x95, 0x3f, 0x69, 0x35, 0xe0, 0x1b, 0x24, 0xc1, 0x9d, 0xc0,
	0x2e, 0x20, 0x6e, 0x85, 0xc6, 0xba, 0x4b, 0x4f, 0x16, 0xa3, 0x65, 0x72, 0x3d, 0x0f, 0xea, 0x6d,
	0x9f, 0xf2, 0x01, 0xb2, 0x2b, 0x98, 0xb8, 0xce, 0xd2, 0xd1, 0xdf, 0x07, 0xde, 0xa2, 0x55, 0x46,
	0xee, 0x7a, 0xc4, 0xbd, 0x91, 0xfd, 0x8a, 0x20, 0x39, 0xba, 0x87, 0x3d, 0x83, 0x07, 0xe5, 0x5e,
	0x28, 0x9d, 0x2b, 0xe9, 0xda, 0x99, 0xf3, 0xa9, 0xab, 0xb7, 0x92, 0x3d, 0x85, 0x29, 0xa1, 0x6d,
	0x7a, 0x72, 0xb2, 0x88, 0x96, 0x63, 0x1e, 0xf7, 0xe5, 0x56, 0xb2, 0x17, 0x30, 0x23, 0xd5, 0x60,
	0x47, 0xa2, 0x69, 0xdd, 0x95, 0x23, 0xfe, 0x27, 0x60, 0x2b, 0x38, 0x27, 0xd4, 0x07, 0x8b, 0x79,
	0x47, 0xc2, 0x52, 0xbe, 0x47, 0x55, 0xed, 0x29, 0x1d, 0xbb, 0x23, 0x1e, 0x7b, 0xb4, 0xeb, 0xc9,
	0x67, 0x07, 0xd8, 0x6b, 0x18, 0xc2, 0x1c, 0xb5, 0x0c, 0xf6, 0xc4, 0xd9, 0x67, 0x1e, 0x7c, 0xd0,
	0x72, 0x70, 0xdf, 0x40, 0x5c, 0x1a, 0x7d, 0xa7, 0xaa, 0x34, 0x76, 0x93, 0x3e, 0x09, 0x93, 0xee,
	0x7e, 0x74, 0x84, 0xcd, 0xc6, 0x31, 0x3e, 0x38, 0xfd, 0x93, 0x27, 0x47, 0x4f, 0xc0, 0x32, 0x98,
	0x6b, 0x63, 0x1b, 0x51, 0xe7, 0x74, 0x9f, 0x97, 0x9a, 0xdc, 0xc0, 0x63, 0x9e, 0xf8, 0xf0, 0xcb,
	0xfd, 0x46, 0x13, 0xbb, 0x84, 0xb3, 0xd2, 0x68, 0xb2, 0xa2, 0xa4, 0x60, 0xf9, 0xe1, 0xe7, 0x21,
	0xf6, 0xde, 0x15, 0x3c, 0x6a, 0x85, 0x25, 0x55, 0xaa, 0x56, 0x90, 0xb1, 0x4e, 0x1c, 0xf9, 0xa6,
	0x8f, 0xf3, 0x8d, 0xa6, 0xec, 0x2b, 0x4c, 0xdc, 0xba, 0xd8, 0x25, 0xc4, 0x35, 0x0a, 0x89, 0x76,
	0x58, 0xfc, 0x69, 0xe8, 0xfe, 0x06, 0x9b, 0x02, 0x2d, 0x1f, 0x28, 0x5b, 0xc2, 0xb4, 0x71, 0x49,
	0x58, 0xfb, 0xbf, 0x62, 0xc0, 0xd9, 0x37, 0x88, 0x7d, 0xd4, 0x2f, 0xab, 0x45, 0xb4, 0x61, 0x8d,
	0x33, 0x1e, 0xf7, 0xe5, 0x56, 0xb2, 0x14, 0xa6, 0x42, 0x4a, 0x8b, 0x5d, 0xe7, 0x06, 0x99, 0xf1,
	0x50, 0xb2, 0x97, 0x90, 0xb4, 0x35, 0xca, 0x0a, 0xf3, 0xbb, 0x83, 0x96, 0xae, 0xfb, 0x87, 0x1c,
	0x7c, 0xf4, 0xf1, 0xa0, 0x65, 0xf6, 0x1e, 0x4e, 0x3f, 0xa1, 0xc6, 0x4e, 0x75, 0xe1, 0xe3, 0x1e,
	0x75, 0x16, 0xfd, 0xb7, 0xb3, 0x22, 0x76, 0xbf, 0xfe, 0xdd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdd, 0xbd, 0xfc, 0x5c, 0x33, 0x03, 0x00, 0x00,
}
