// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: state.proto

package consensuspb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ConsensusRoot struct {
	TermId               uint64   `protobuf:"varint,1,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PeriodRoot           []byte   `protobuf:"bytes,3,opt,name=period_root,json=periodRoot,proto3" json:"period_root,omitempty"`
	EventRoot            []byte   `protobuf:"bytes,4,opt,name=event_root,json=eventRoot,proto3" json:"event_root,omitempty"`
	ReportRoot           []byte   `protobuf:"bytes,5,opt,name=report_root,json=reportRoot,proto3" json:"report_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusRoot) Reset()         { *m = ConsensusRoot{} }
func (m *ConsensusRoot) String() string { return proto.CompactTextString(m) }
func (*ConsensusRoot) ProtoMessage()    {}
func (*ConsensusRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{0}
}
func (m *ConsensusRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusRoot.Unmarshal(m, b)
}
func (m *ConsensusRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusRoot.Marshal(b, m, deterministic)
}
func (m *ConsensusRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusRoot.Merge(m, src)
}
func (m *ConsensusRoot) XXX_Size() int {
	return xxx_messageInfo_ConsensusRoot.Size(m)
}
func (m *ConsensusRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusRoot.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusRoot proto.InternalMessageInfo

func (m *ConsensusRoot) GetTermId() uint64 {
	if m != nil {
		return m.TermId
	}
	return 0
}

func (m *ConsensusRoot) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConsensusRoot) GetPeriodRoot() []byte {
	if m != nil {
		return m.PeriodRoot
	}
	return nil
}

func (m *ConsensusRoot) GetEventRoot() []byte {
	if m != nil {
		return m.EventRoot
	}
	return nil
}

func (m *ConsensusRoot) GetReportRoot() []byte {
	if m != nil {
		return m.ReportRoot
	}
	return nil
}

type CouncilRoot struct {
	PhaseNum             uint32   `protobuf:"varint,1,opt,name=phase_num,json=phaseNum,proto3" json:"phase_num,omitempty"`
	ParticipatorRoot     []byte   `protobuf:"bytes,2,opt,name=participator_root,json=participatorRoot,proto3" json:"participator_root,omitempty"`
	MinerRoot            []byte   `protobuf:"bytes,3,opt,name=miner_root,json=minerRoot,proto3" json:"miner_root,omitempty"`
	HeightRoot           []byte   `protobuf:"bytes,4,opt,name=height_root,json=heightRoot,proto3" json:"height_root,omitempty"`
	Content              []byte   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CouncilRoot) Reset()         { *m = CouncilRoot{} }
func (m *CouncilRoot) String() string { return proto.CompactTextString(m) }
func (*CouncilRoot) ProtoMessage()    {}
func (*CouncilRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{1}
}
func (m *CouncilRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CouncilRoot.Unmarshal(m, b)
}
func (m *CouncilRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CouncilRoot.Marshal(b, m, deterministic)
}
func (m *CouncilRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CouncilRoot.Merge(m, src)
}
func (m *CouncilRoot) XXX_Size() int {
	return xxx_messageInfo_CouncilRoot.Size(m)
}
func (m *CouncilRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_CouncilRoot.DiscardUnknown(m)
}

var xxx_messageInfo_CouncilRoot proto.InternalMessageInfo

func (m *CouncilRoot) GetPhaseNum() uint32 {
	if m != nil {
		return m.PhaseNum
	}
	return 0
}

func (m *CouncilRoot) GetParticipatorRoot() []byte {
	if m != nil {
		return m.ParticipatorRoot
	}
	return nil
}

func (m *CouncilRoot) GetMinerRoot() []byte {
	if m != nil {
		return m.MinerRoot
	}
	return nil
}

func (m *CouncilRoot) GetHeightRoot() []byte {
	if m != nil {
		return m.HeightRoot
	}
	return nil
}

func (m *CouncilRoot) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsensusRoot)(nil), "consensuspb.ConsensusRoot")
	proto.RegisterType((*CouncilRoot)(nil), "consensuspb.CouncilRoot")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_a888679467bb7853) }

var fileDescriptor_a888679467bb7853 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0xe5, 0xb6, 0xb4, 0x64, 0x42, 0x25, 0xc8, 0x86, 0x48, 0x80, 0x1a, 0x75, 0x15, 0x09,
	0x89, 0x0d, 0x47, 0xe8, 0x8a, 0x0d, 0x8b, 0x5c, 0x20, 0x72, 0x93, 0x11, 0xb1, 0x84, 0x3d, 0x96,
	0x3d, 0xe1, 0x4a, 0xac, 0xb9, 0x21, 0xea, 0x18, 0x8b, 0x76, 0xf9, 0xdf, 0xf7, 0x7c, 0x3d, 0x19,
	0xca, 0xc8, 0x9a, 0xf1, 0xc5, 0x07, 0x62, 0xaa, 0xca, 0x81, 0x5c, 0x44, 0x17, 0xe7, 0xe8, 0x8f,
	0xfb, 0x6f, 0x05, 0xdb, 0x43, 0xce, 0x1d, 0x11, 0x57, 0xf7, 0xb0, 0x61, 0x0c, 0xb6, 0x37, 0x63,
	0xad, 0x1a, 0xd5, 0xae, 0xba, 0xf5, 0x29, 0xbe, 0x8d, 0xd5, 0x23, 0x14, 0x6c, 0x2c, 0x46, 0xd6,
	0xd6, 0xd7, 0x8b, 0x46, 0xb5, 0xcb, 0xee, 0x1f, 0x54, 0x3b, 0x28, 0x3d, 0x06, 0x43, 0x63, 0x1f,
	0x88, 0xb8, 0x5e, 0x36, 0xaa, 0xbd, 0xe9, 0x20, 0x21, 0xd9, 0x7d, 0x02, 0xc0, 0x2f, 0x74, 0x9c,
	0xfa, 0x95, 0xf4, 0x85, 0x10, 0xa9, 0x77, 0x50, 0x06, 0xf4, 0x14, 0xfe, 0xfa, 0xab, 0x74, 0x9f,
	0xd0, 0xe9, 0xc1, 0xfe, 0x47, 0x41, 0x79, 0xa0, 0xd9, 0x0d, 0xe6, 0x53, 0x0e, 0x1e, 0xa0, 0xf0,
	0x93, 0x8e, 0xd8, 0xbb, 0xd9, 0x8a, 0xe9, 0xb6, 0xbb, 0x16, 0xf0, 0x3e, 0xdb, 0xea, 0x19, 0xee,
	0xbc, 0x0e, 0x6c, 0x06, 0xe3, 0x35, 0x53, 0x48, 0x9b, 0x0b, 0xd9, 0xbc, 0x3d, 0x2f, 0xb2, 0x99,
	0x35, 0x0e, 0xc3, 0xb9, 0x79, 0x21, 0x24, 0x9b, 0x4d, 0x68, 0x3e, 0xa6, 0x0b, 0x73, 0x48, 0x48,
	0x1e, 0xd4, 0xb0, 0x19, 0xc8, 0x31, 0xba, 0xac, 0x9d, 0xe3, 0x71, 0x2d, 0x3f, 0xfe, 0xfa, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0xfd, 0x21, 0xd7, 0x80, 0x01, 0x00, 0x00,
}
